<?php

namespace App\Integration\Tests;

use App\Entity\User;
use App\Service\UserService;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Input\ArrayInput;

class IntegrationServiceTest extends KernelTestCase
{
    /**
     * @var \App\Service\UserService
     */
    protected $userService;
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $kernel = self::createKernel();
        $application = new Application($kernel);
        $application->setAutoExit(false);
        try {
            $application->run(new ArrayInput([
                'command' => 'doctrine:database:drop',
                '--force' => true,
            ]));
        } catch (\Exception $e) {
        }
        try {
            $application->run(new ArrayInput([
                'command' => 'doctrine:database:create'
            ]));
        } catch (\Exception $e) {
        }
        try {
            $application->run(new ArrayInput([
                'command' => 'doctrine:migrations:migrate',
                '--no-interaction' => true
            ]));
        } catch (\Exception $e) {
        }
        try {
            $application->run(new ArrayInput([
                'command' => 'doctrine:fixtures:load',
                '--append' => true
            ]));
        } catch (\Exception $e) {
        }

        $userRepository = $kernel->getContainer()->get('doctrine')->getRepository(User::class);
        $this->userService = new UserService($userRepository);
    }

    public function testSomething()
    {
        $result = $this->userService->getAmount();
        $this->assertEquals(5,$result);
    }
}
